// Placeholder shared enums/interfaces — extended as each phase introduces real contracts.

export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  RESTAURANT = 'RESTAURANT',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  ADMIN = 'ADMIN',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  RESTAURANT_PENDING = 'RESTAURANT_PENDING',
  RESTAURANT_ACCEPTED = 'RESTAURANT_ACCEPTED',
  RESTAURANT_REJECTED = 'RESTAURANT_REJECTED',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DELIVERY_ACCEPTED = 'DELIVERY_ACCEPTED',
  PICKED_UP = 'PICKED_UP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
  RESTAURANT_CANCELLED = 'RESTAURANT_CANCELLED',
  DELIVERY_CANCELLED = 'DELIVERY_CANCELLED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
}

export interface PaginatedResult<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
}
